exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:

  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  # - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-illegal-windows-names
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
  - id: name-tests-test
    args: ['--pytest-test-first']
    files: ^tests/dist_classicrl/.*\.py
  - id: pretty-format-json
    args: ['--autofix', '--no-ensure-ascii', '--no-sort-keys']
  - id: requirements-txt-fixer
  - id: trailing-whitespace

# If you want to automatically "modernize" your Python code:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
    args: ['--py38-plus']

## If you want to avoid flake8 errors due to unused vars or imports:
# - repo: https://github.com/PyCQA/autoflake
#   rev: v2.3.1
#   hooks:
#   - id: autoflake
#     args: [
#       --in-place,
#       --remove-all-unused-imports,
#       --remove-unused-variables,
#     ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.1
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.402
  hooks:
  - id: pyright

- repo: https://github.com/jsh9/pydoclint
  rev: 0.6.7
  hooks:
  - id: pydoclint
    files: ^src/.*\.py
    exclude: ^src/dist_classicrl/old/.*\.py



# - repo: https://github.com/pre-commit/mirrors-pylint
#   rev: v3.0.0a5  # Use latest stable Pylint
#   hooks:
#     - id: pylint

# - repo: https://github.com/PyCQA/isort
#   rev: 6.0.1
#   hooks:
#   - id: isort


# - repo: https://github.com/psf/black
#   rev: 25.1.0
#   hooks:
#   - id: black
#     language_version: python3

# # If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: 1.19.1
#   hooks:
#   - id: blacken-docs
#     additional_dependencies:
#     - black

# - repo: https://github.com/PyCQA/flake8
#   rev: 7.1.1
#   hooks:
#   - id: flake8
  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]

# Check for misspells in documentation files:
# - repo: https://github.com/codespell-project/codespell
#   rev: v2.4.1
#   hooks:
#   - id: codespell

## Check for dead code:
# - repo: https://github.com/pre-commit/mirrors-vulture
#   rev: v2.11
#   hooks:
#   - id: vulture

## Security scanner for Python code:
# - repo: https://github.com/PyCQA/bandit
#   rev: 1.7.5
#   hooks:
#   - id: bandit

## Check dependencies for security vulnerabilities:
# - repo: https://github.com/pre-commit/mirrors-pip-audit
#   rev: v2.7.1
#   hooks:
#   - id: pip-audit

# darglint
# cspell
# docformatter
